import { X, Printer } from 'lucide-react';
import { formatDate, durationText, STATUS_STYLES, progressHex, COLUMN_DEFINITIONS } from '../utils/helpers';

function SummaryCard({ label, value, colorClass }) {
  return (
    <div className="rounded-md border border-gray-200 bg-white p-4 text-center shadow-sm">
      <div className={`text-2xl font-bold ${colorClass}`}>{value}</div>
      <div className="text-xs text-gray-500">{label}</div>
    </div>
  );
}

const renderers = {
  id: (p) => p.id,
  title: (p) => <span className="font-semibold text-[#1a1a2e]">{p.title}</span>,
  project: (p) => p.project,
  status: (p) => {
    const style = STATUS_STYLES[p.status] || STATUS_STYLES.Draft;
    return (
      <span
        className="inline-flex rounded-full px-2 py-0.5 text-xs font-medium"
        style={{ color: style.text, backgroundColor: style.bg }}
      >
        {p.status}
      </span>
    );
  },
  billedPercent: (p) => (
    <div className="w-20">
      <div className="h-1.5 w-full rounded bg-gray-200">
        <div
          className="h-1.5 rounded"
          style={{ width: `${p.billedPercent}%`, backgroundColor: progressHex(p.billedPercent) }}
        />
      </div>
      <span className="text-[10px] text-gray-500">{p.billedPercent}%</span>
    </div>
  ),
  startDate: (p) => formatDate(p.startDate),
  endDate: (p) => formatDate(p.endDate),
  duration: (p) => durationText(p),
  assignedTo: (p) => p.assignedTo,
  createdBy: (p) => p.createdBy,
  tags: (p) => (p.tags || []).join(', '),
  comments: (p) => p.comments,
  milestoneStatus: (p) => p.milestoneStatus,
  department: (p) => p.department,
  favourite: (p) => (p.favourite ? 'Yes' : 'No'),
};

export default function PreviewModal({ rows, visibleColumns, onClose }) {
  const today = '2026-06-15';
  const total = rows.length;
  const active = rows.filter((r) => r.status === 'Active').length;
  const completed = rows.filter((r) => r.status === 'Completed').length;
  const onHold = rows.filter((r) => r.status === 'On Hold').length;
  const delayed = rows.filter((r) => r.endDate < today && r.status !== 'Completed').length;

  const handlePrint = () => {
    window.print();
  };

  const previewColumns = COLUMN_DEFINITIONS.filter(
    (col) => col.key !== 'select' && visibleColumns.includes(col.key)
  );

  return (
    <div className="print-scope fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
      <div className="flex max-h-[90vh] w-full max-w-[900px] flex-col overflow-hidden rounded-lg bg-white shadow-xl">
        {/* Header */}
        <div className="flex items-center justify-between bg-navy px-4 py-3 text-white no-print">
          <div className="flex items-center gap-3">
            <div>
              <div className="text-sm font-semibold">Project Management Report</div>
              <div className="text-xs text-gray-300">
                Generated on {formatDate(today)} · {rows.length} rows
              </div>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handlePrint}
              className="inline-flex items-center gap-1.5 rounded-md bg-white px-3 py-1.5 text-xs font-medium text-navy hover:bg-gray-100"
            >
              <Printer className="h-4 w-4" />
              Print / Download PDF
            </button>
            <button
              type="button"
              onClick={onClose}
              className="rounded-md p-1.5 hover:bg-white/10"
              aria-label="Close"
            >
              <X className="h-5 w-5" />
            </button>
          </div>
        </div>

        {/* Scrollable body */}
        <div className="flex-1 overflow-auto p-6">
          {/* Report header */}
          <div className="mb-6 flex items-start justify-between border-b border-gray-200 pb-4">
            <div>
              <div className="mb-1 h-10 w-10 rounded bg-gray-200" />
              <h2 className="text-lg font-bold text-[#1a1a2e]">Project Management Report</h2>
              <p className="text-xs text-gray-500">
                Date range: {formatDate(today)} to {formatDate(today)}
              </p>
              <p className="text-xs text-gray-500">
                Generated by: ERP System · {new Date().toLocaleString()}
              </p>
            </div>
            <div className="text-right text-xs text-gray-400">
              <div>Confidential</div>
              <div>ERP System</div>
            </div>
          </div>

          {/* Summary metrics */}
          <div className="mb-6 grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-5">
            <SummaryCard label="Total Projects" value={total} colorClass="text-gray-800" />
            <SummaryCard label="Active" value={active} colorClass="text-blue-600" />
            <SummaryCard label="Completed" value={completed} colorClass="text-green-600" />
            <SummaryCard label="Delayed" value={delayed} colorClass="text-red-600" />
            <SummaryCard label="On Hold" value={onHold} colorClass="text-gray-600" />
          </div>

          {/* Data table */}
          <table className="print-table w-full border-collapse">
            <thead>
              <tr className="bg-gray-50">
                {previewColumns.map((col) => (
                  <th
                    key={col.key}
                    className="border border-gray-200 px-2 py-2 text-left text-xs font-semibold uppercase text-[#9aa0ac]"
                  >
                    {col.label}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {rows.map((p) => (
                <tr key={p.id} className="bg-white">
                  {previewColumns.map((col) => (
                    <td key={col.key} className="border border-gray-200 px-2 py-2 text-xs text-gray-700">
                      {renderers[col.key] ? renderers[col.key](p) : p[col.key]}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>

          {previewColumns.length === 0 && (
            <div className="py-8 text-center text-sm text-gray-500">
              No columns selected for the preview.
            </div>
          )}

          {/* Footer */}
          <div className="mt-6 flex items-center justify-between border-t border-gray-200 pt-3 text-xs text-gray-400">
            <div>Page 1 of 1</div>
            <div>Confidential · ERP System</div>
          </div>
        </div>
      </div>
    </div>
  );
}
